import AuthContext from "@/context/AuthContext";
import Navbar from "./components/Navbar";

import "./globals.css";
import { Open_Sans } from "next/font/google";
import ReduxProvider from "./ReduxProvider";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en" className={openSans.className}>
      <body className="w-full max-w-screen-md bg-red-100 overflow-auto mx-auto">
        <AuthContext>
          <ReduxProvider>
            <header className="sticky top-0 bg-red-100 z-10 border-b">
              <Navbar />
            </header>
            <main>{children}</main>
            <div id="portal"></div>
          </ReduxProvider>
        </AuthContext>
      </body>
    </html>
  );
}